name: Run Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Bun
      run: |
        curl -fsSL https://bun.sh/install | bash
        echo "$HOME/.bun" >> $GITHUB_PATH

    - name: Check Bun version
      run: bun --version

    - name: Install dependencies
      run: bun install

    - name: Run tests
      run: bun test
